### ISSUE TITLE
Run locally ?

### ISSUE THREAD

**Issue by Shuunen** [UnlyEd/airtable-backups-boilerplate#11]
Hi there,

This project looks great, is there any way to use it without AWS ? like just run it to have backups on my hard drive

Thanks

**Comment by Vadorequest** [comment]
It's possible to adapt the code to store the files into the local filesystem, instead of AWS, but that's not something built-in at this time.

The idea would be to mock an event, similar to what we've done inside tests:
https://github.com/UnlyEd/airtable-backups-boilerplate/blob/master/src/utils/airtableParser.test.js#L12

And then call the `fetchDataFromAirtable` function, and store the result into a file.

I guess it'd rather easily be done using a script and a yarn command.

**Comment by Shuunen** [comment]
thanks for the heads up, I'll give it a shot for my next backup 👍

it's sad to see that Airtable clearly don't want people to get their data easily, usually you can go to any account settings and click on a "download my data" like with Google, Facebook, you name it... and here with airtable nothing, you need to go to each table to extract one view in csv which doesn't have attachments 👀😒

**Comment by Vadorequest** [comment]
Yeah, there are alternatives though. (usually paid ones)

I wrote extensively on that matter on the forum: https://community.airtable.com/t/state-of-airtable-backup-restoration-2020-summary-of-existing-tools/36124

**Comment by Vadorequest** [comment]
I'm closing this, hope it's solved for you :) Let me know otherwise!

**Comment by Shuunen** [comment]
@Vadorequest I think about boycotting Airtable so yes it will be solved the hard way 😄

**Comment by Vadorequest** [comment]
Look at Budibase, NocoDB as alternatives :)
